"""
Monitoring Module for Quantitative Trading System.

Provides comprehensive monitoring, alerting, and observability including:
- Prometheus metrics collection
- Grafana dashboard configurations
- Alerting system with multiple notification channels
- Structured logging framework
- Health checks and synthetic monitoring
- Performance attribution analysis
- Model diagnostics and drift detection
"""

from quant_trading.monitoring.metrics import (
    MetricsCollector,
    track_latency,
    track_latency_async,
    count_calls,
)

from quant_trading.monitoring.alerts import (
    Alert,
    AlertRule,
    AlertSeverity,
    AlertCategory,
    AlertStatus,
    AlertManager,
    NotificationChannel,
    LogChannel,
    SlackChannel,
    EmailChannel,
    PagerDutyChannel,
    WebhookChannel,
    EscalationPolicy,
    create_default_alert_rules,
)

from quant_trading.monitoring.dashboards import (
    Panel,
    PanelType,
    Dashboard,
    PrometheusTarget,
    DashboardVariable,
    DashboardProvisioner,
    create_trading_overview_dashboard,
    create_risk_dashboard,
    create_system_health_dashboard,
    create_data_quality_dashboard,
)

from quant_trading.monitoring.logging import (
    LogLevel,
    LogCategory,
    LogContext,
    BoundLogger,
    StructuredLogRecord,
    JsonFormatter,
    ConsoleFormatter,
    AsyncLogHandler,
    RotatingFileHandler,
    ErrorTracker,
    ErrorGroup,
    StructuredLogger,
    LoggingConfig,
    LoggingManager,
    TradingLogger,
    RiskLogger,
    AuditLogger,
    configure_logging,
    get_logger,
    get_context,
    bind,
    unbind,
    clear_context,
    trading_logger,
    risk_logger,
    audit_logger,
)

from quant_trading.monitoring.health import (
    HealthStatus,
    HealthCheckResult,
    HealthCheck,
    DatabaseHealthCheck,
    TCPHealthCheck,
    HTTPHealthCheck,
    RedisHealthCheck,
    RabbitMQHealthCheck,
    MemoryHealthCheck,
    DiskHealthCheck,
    CPUHealthCheck,
    CustomHealthCheck,
    SyntheticTestResult,
    SyntheticTest,
    OrderFlowSyntheticTest,
    DataFeedSyntheticTest,
    ModelCalibrationSyntheticTest,
    HealthReport,
    CircuitState,
    CircuitBreaker,
    HealthManager,
    get_health_manager,
    register_default_checks,
    with_circuit_breaker,
    health_check_endpoint,
    liveness_probe,
    readiness_probe,
)

from quant_trading.monitoring.attribution import (
    AttributionPeriod,
    ReturnDecomposition,
    RiskAttribution,
    TradeAttribution,
    BrinsonAttribution,
    FactorExposure,
    PerformanceReport,
    ReturnsAttributor,
    RiskAttributor,
    BrinsonAttributor,
    TradeAttributor,
    FactorAttributor,
    PerformanceAttributionEngine,
)

from quant_trading.monitoring.diagnostics import (
    ModelType,
    DiagnosticStatus,
    CalibrationMetrics,
    DriftMetrics,
    ParameterStability,
    ForecastAccuracy,
    BacktestComparison,
    ModelDiagnosticReport,
    CalibrationMonitor,
    DriftDetector,
    ParameterStabilityAnalyzer,
    ForecastAccuracyTracker,
    BacktestLiveComparator,
    ModelDiagnosticsEngine,
    get_diagnostics_engine,
)

from quant_trading.monitoring.runbooks import (
    RunbookCategory,
    StepStatus,
    RunbookStep,
    Runbook,
    RunbookRegistry,
    create_high_drawdown_runbook,
    create_data_staleness_runbook,
    create_model_calibration_failure_runbook,
    create_system_high_cpu_runbook,
    create_order_rejection_runbook,
    create_cointegration_breakdown_runbook,
    create_default_runbooks,
    get_default_registry,
)

__all__ = [
    # Metrics
    "MetricsCollector",
    "track_latency",
    "track_latency_async",
    "count_calls",
    # Alerts
    "Alert",
    "AlertRule",
    "AlertSeverity",
    "AlertCategory",
    "AlertStatus",
    "AlertManager",
    "NotificationChannel",
    "LogChannel",
    "SlackChannel",
    "EmailChannel",
    "PagerDutyChannel",
    "WebhookChannel",
    "EscalationPolicy",
    "create_default_alert_rules",
    # Dashboards
    "Panel",
    "PanelType",
    "Dashboard",
    "PrometheusTarget",
    "DashboardVariable",
    "DashboardProvisioner",
    "create_trading_overview_dashboard",
    "create_risk_dashboard",
    "create_system_health_dashboard",
    "create_data_quality_dashboard",
    # Logging
    "LogLevel",
    "LogCategory",
    "LogContext",
    "BoundLogger",
    "StructuredLogRecord",
    "JsonFormatter",
    "ConsoleFormatter",
    "AsyncLogHandler",
    "RotatingFileHandler",
    "ErrorTracker",
    "ErrorGroup",
    "StructuredLogger",
    "LoggingConfig",
    "LoggingManager",
    "TradingLogger",
    "RiskLogger",
    "AuditLogger",
    "configure_logging",
    "get_logger",
    "get_context",
    "bind",
    "unbind",
    "clear_context",
    "trading_logger",
    "risk_logger",
    "audit_logger",
    # Health
    "HealthStatus",
    "HealthCheckResult",
    "HealthCheck",
    "DatabaseHealthCheck",
    "TCPHealthCheck",
    "HTTPHealthCheck",
    "RedisHealthCheck",
    "RabbitMQHealthCheck",
    "MemoryHealthCheck",
    "DiskHealthCheck",
    "CPUHealthCheck",
    "CustomHealthCheck",
    "SyntheticTestResult",
    "SyntheticTest",
    "OrderFlowSyntheticTest",
    "DataFeedSyntheticTest",
    "ModelCalibrationSyntheticTest",
    "HealthReport",
    "CircuitState",
    "CircuitBreaker",
    "HealthManager",
    "get_health_manager",
    "register_default_checks",
    "with_circuit_breaker",
    "health_check_endpoint",
    "liveness_probe",
    "readiness_probe",
    # Attribution
    "AttributionPeriod",
    "ReturnDecomposition",
    "RiskAttribution",
    "TradeAttribution",
    "BrinsonAttribution",
    "FactorExposure",
    "PerformanceReport",
    "ReturnsAttributor",
    "RiskAttributor",
    "BrinsonAttributor",
    "TradeAttributor",
    "FactorAttributor",
    "PerformanceAttributionEngine",
    # Diagnostics
    "ModelType",
    "DiagnosticStatus",
    "CalibrationMetrics",
    "DriftMetrics",
    "ParameterStability",
    "ForecastAccuracy",
    "BacktestComparison",
    "ModelDiagnosticReport",
    "CalibrationMonitor",
    "DriftDetector",
    "ParameterStabilityAnalyzer",
    "ForecastAccuracyTracker",
    "BacktestLiveComparator",
    "ModelDiagnosticsEngine",
    "get_diagnostics_engine",
    # Runbooks
    "RunbookCategory",
    "StepStatus",
    "RunbookStep",
    "Runbook",
    "RunbookRegistry",
    "create_high_drawdown_runbook",
    "create_data_staleness_runbook",
    "create_model_calibration_failure_runbook",
    "create_system_high_cpu_runbook",
    "create_order_rejection_runbook",
    "create_cointegration_breakdown_runbook",
    "create_default_runbooks",
    "get_default_registry",
]
